### ISSUE TITLE
Add to DRF's Third Party Resources

### ISSUE THREAD

**Issue by jpadilla** [dealertrack/django-rest-framework-braces#1]
Looks great! You might want to add this to our list of existing third party resources.

http://www.django-rest-framework.org/topics/third-party-resources/#existing-third-party-packages

**Comment by miki725** [comment]
Thats a great idea! WIll do!

**Comment by miki725** [comment]
for reference https://github.com/tomchristie/django-rest-framework/pull/3118

**Comment by miki725** [comment]
thanks @jpadilla for the idea and thanks for merging the other PR!
